"""Added all relationship what can

Revision ID: 0a2ed0e215c8
Revises: 2dc3aae62a35
Create Date: 2020-05-31 17:30:34.591298

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a2ed0e215c8'
down_revision = '2dc3aae62a35'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
