"""Add date when create and modified

Revision ID: 1841a1032d45
Revises: 2dc3aae62a35
Create Date: 2020-06-02 20:51:07.991634

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1841a1032d45'
down_revision = '2dc3aae62a35'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answer', sa.Column('created', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('answer', sa.Column('modified', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('question', sa.Column('created', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('question', sa.Column('modified', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('quiz', sa.Column('created', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('quiz', sa.Column('modified', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quiz', 'modified')
    op.drop_column('quiz', 'created')
    op.drop_column('question', 'modified')
    op.drop_column('question', 'created')
    op.drop_column('answer', 'modified')
    op.drop_column('answer', 'created')
    # ### end Alembic commands ###
