"""Fix name of Answer column from quiz_id to question_id

Revision ID: 2dc3aae62a35
Revises: 4e781aa48aac
Create Date: 2020-05-31 17:16:35.298723

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2dc3aae62a35'
down_revision = '4e781aa48aac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answer', sa.Column('question_id', sa.Integer(), nullable=True))
    op.drop_constraint('answer_quiz_id_fkey', 'answer', type_='foreignkey')
    op.create_foreign_key(None, 'answer', 'question', ['question_id'], ['id'])
    op.drop_column('answer', 'quiz_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answer', sa.Column('quiz_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'answer', type_='foreignkey')
    op.create_foreign_key('answer_quiz_id_fkey', 'answer', 'question', ['quiz_id'], ['id'])
    op.drop_column('answer', 'question_id')
    # ### end Alembic commands ###
