"""Added foreign key

Revision ID: 4e781aa48aac
Revises: c85370749576
Create Date: 2020-05-31 17:15:04.845569

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e781aa48aac'
down_revision = 'c85370749576'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answer', sa.Column('quiz_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'answer', 'question', ['quiz_id'], ['id'])
    op.add_column('question', sa.Column('quiz_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'question', 'quiz', ['quiz_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'question', type_='foreignkey')
    op.drop_column('question', 'quiz_id')
    op.drop_constraint(None, 'answer', type_='foreignkey')
    op.drop_column('answer', 'quiz_id')
    # ### end Alembic commands ###
