"""Add timezone for datetime

Revision ID: 5c4ddd44f0df
Revises: 00f9aaeecd3f
Create Date: 2020-07-22 19:38:13.780735

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c4ddd44f0df'
down_revision = '00f9aaeecd3f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answer', sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('answer', sa.Column('modified', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('question', sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('question', sa.Column('modified', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('quiz', sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('quiz', sa.Column('modified', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quiz', 'modified')
    op.drop_column('quiz', 'created')
    op.drop_column('question', 'modified')
    op.drop_column('question', 'created')
    op.drop_column('answer', 'modified')
    op.drop_column('answer', 'created')
    # ### end Alembic commands ###
