"""Fix question relationship column

Revision ID: c78a7d0dea72
Revises: 0a2ed0e215c8
Create Date: 2020-05-31 17:32:45.088533

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c78a7d0dea72'
down_revision = '0a2ed0e215c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
