version: '3'
services:
  database:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        POSTGRES_USER: 'unicorn_user'
    #        POSTGRES_USER: "${POSTGRES_USER}"
    #    image: "postgres" # use latest official postgres version
    ports:
        - "${HOSTPORT}:${PGSQLPORT}"
    env_file:
      - db.env # configure postgres
    volumes:
      - database-data:/var/lib/postgresql/data/ # persist data even if container shuts down
volumes:
  database-data: # named volumes can be managed easier using docker-compose
